library(shiny)

# In this app, we include the datagridXL using an adhoc js file. It is easier to incorporate the
# grid into a single app than it is to make a generic package allowing the grid to be put into any
# app.  Also, we will keep the grid a bit separate from the input$ and output$ reactivity.  We don't
# need every cell change being sent to the server, and we don't want the grid to frequently update
# itself based on its inputs.  We will try to keep the grid logic in the grid.  In other words,
# we are requiring the Shiny developer to use JS.

datagridxlUI <- function(id = "datagrid", width = "100%", height = "400px"){

	# Create basic html tag
	style <- htmltools::css(width = validateCssUnit(width), height = validateCssUnit(height))
	args <- list(id = id,
				 class = "datagridxlr",
				 style = style)
	grid <-do.call(div, args)

	# Prepare dependency
	path <- system.file(package = "datagridxlr")
	deps <- htmltools::htmlDependency(
		name = "datagridxlr",
		version = packageVersion("datagridxlr"),
		src = c(file = path),
		script = c("datagridxl2.js"),
		stylesheet = "datagridxlr.css"
	)

	# Attach dependency and return
	htmltools::attachDependencies(grid, deps)
}

addResourcePath("assets", system.file("demo/nonreactive/assets", package = "datagridxlr"))

ui <- fluidPage(
	tags$head(tags$script(src= "assets/this_app.js")),
	actionButton("add_mtcars_data", "Add mtcars Data", class = "btn-primary"),
	actionButton("add_iris_data", "Add iris Data", class = "btn-primary"),
	tags$button(class = "btn btn-primary",
				onClick = "sendGridData()",
				"Send Data to DT"),
	datagridxlUI(),
	DT::DTOutput("dt")

)

server <- function(input, output, session) {
	observe({
		options <- list(rowHeaderLabelPrefix = "test ",
						rowHeaderWidth = 300,
						allowEditCells = FALSE)
		session$sendCustomMessage(type = "create-grid", message = datagridxl(mtcars, options))
	}) %>%
		bindEvent(input$add_mtcars_data)

	observe({
		session$sendCustomMessage(type = "create-grid", message = datagridxl(iris))
	}) %>%
		bindEvent(input$add_iris_data)

	output$dt <- DT::renderDT({
		req(input$griddata)
		input$griddata
	})
}

shinyApp(ui, server)

# temp <- c(Sepal.Length = "5.1", Sepal.Width = "3.5", Petal.Length = "1.4",
# 		  Petal.Width = "0.2", Species = "setosa", Sepal.Length = "4.9",
# 		  Sepal.Width = "3.0", Petal.Length = "1.4", Petal.Width = "0.2",
# 		  Species = "setosa", Sepal.Length = "4.7", Sepal.Width = "3.2",
# 		  Petal.Length = "1.3", Petal.Width = "0.2", Species = "setosa",
# 		  Sepal.Length = "4.6", Sepal.Width = "3.1", Petal.Length = "1.5",
# 		  Petal.Width = "0.2", Species = "setosa", Sepal.Length = "5.0",
# 		  Sepal.Width = "3.6", Petal.Length = "1.4", Petal.Width = "0.2",
# 		  Species = "setosa", Sepal.Length = "5.4", Sepal.Width = "3.9",
# 		  Petal.Length = "1.7", Petal.Width = "0.4", Species = "setosa",
# 		  Sepal.Length = "4.6", Sepal.Width = "3.4", Petal.Length = "1.4",
# 		  Petal.Width = "0.3", Species = "setosa", Sepal.Length = "5.0",
# 		  Sepal.Width = "3.4", Petal.Length = "1.5", Petal.Width = "0.2",
# 		  Species = "setosa", Sepal.Length = "4.4", Sepal.Width = "2.9",
# 		  Petal.Length = "1.4", Petal.Width = "0.2", Species = "setosa",
# 		  Sepal.Length = "4.9", Sepal.Width = "3.1", Petal.Length = "1.5",
# 		  Petal.Width = "0.1", Species = "setosa", Sepal.Length = "5.4",
# 		  Sepal.Width = "3.7", Petal.Length = "1.5", Petal.Width = "0.2",
# 		  Species = "setosa", Sepal.Length = "4.8", Sepal.Width = "3.4",
# 		  Petal.Length = "1.6", Petal.Width = "0.2", Species = "setosa",
# 		  Sepal.Length = "4.8", Sepal.Width = "3.0", Petal.Length = "1.4",
# 		  Petal.Width = "0.1", Species = "setosa", Sepal.Length = "4.3",
# 		  Sepal.Width = "3.0", Petal.Length = "1.1", Petal.Width = "0.1",
# 		  Species = "setosa", Sepal.Length = "5.8", Sepal.Width = "4.0",
# 		  Petal.Length = "1.2", Petal.Width = "0.2", Species = "setosa",
# 		  Sepal.Length = "5.7", Sepal.Width = "4.4", Petal.Length = "1.5",
# 		  Petal.Width = "0.4", Species = "setosa", Sepal.Length = "5.4",
# 		  Sepal.Width = "3.9", Petal.Length = "1.3", Petal.Width = "0.4",
# 		  Species = "setosa", Sepal.Length = "5.1", Sepal.Width = "3.5",
# 		  Petal.Length = "1.4", Petal.Width = "0.3", Species = "setosa",
# 		  Sepal.Length = "5.7", Sepal.Width = "3.8", Petal.Length = "1.7",
# 		  Petal.Width = "0.3", Species = "setosa", Sepal.Length = "5.1",
# 		  Sepal.Width = "3.8", Petal.Length = "1.5", Petal.Width = "0.3",
# 		  Species = "setosa", Sepal.Length = "5.4", Sepal.Width = "3.4",
# 		  Petal.Length = "1.7", Petal.Width = "0.2", Species = "setosa",
# 		  Sepal.Length = "5.1", Sepal.Width = "3.7", Petal.Length = "1.5",
# 		  Petal.Width = "0.4", Species = "setosa", Sepal.Length = "4.6",
# 		  Sepal.Width = "3.6", Petal.Length = "1.0", Petal.Width = "0.2",
# 		  Species = "setosa", Sepal.Length = "5.1", Sepal.Width = "3.3",
# 		  Petal.Length = "1.7", Petal.Width = "0.5", Species = "setosa",
# 		  Sepal.Length = "4.8", Sepal.Width = "3.4", Petal.Length = "1.9",
# 		  Petal.Width = "0.2", Species = "setosa", Sepal.Length = "5.0",
# 		  Sepal.Width = "3.0", Petal.Length = "1.6", Petal.Width = "0.2",
# 		  Species = "setosa", Sepal.Length = "5.0", Sepal.Width = "3.4",
# 		  Petal.Length = "1.6", Petal.Width = "0.4", Species = "setosa",
# 		  Sepal.Length = "5.2", Sepal.Width = "3.5", Petal.Length = "1.5",
# 		  Petal.Width = "0.2", Species = "setosa", Sepal.Length = "5.2",
# 		  Sepal.Width = "3.4", Petal.Length = "1.4", Petal.Width = "0.2",
# 		  Species = "setosa", Sepal.Length = "4.7", Sepal.Width = "3.2",
# 		  Petal.Length = "1.6", Petal.Width = "0.2", Species = "setosa",
# 		  Sepal.Length = "4.8", Sepal.Width = "3.1", Petal.Length = "1.6",
# 		  Petal.Width = "0.2", Species = "setosa", Sepal.Length = "5.4",
# 		  Sepal.Width = "3.4", Petal.Length = "1.5", Petal.Width = "0.4",
# 		  Species = "setosa", Sepal.Length = "5.2", Sepal.Width = "4.1",
# 		  Petal.Length = "1.5", Petal.Width = "0.1", Species = "setosa",
# 		  Sepal.Length = "5.5", Sepal.Width = "4.2", Petal.Length = "1.4",
# 		  Petal.Width = "0.2", Species = "setosa", Sepal.Length = "4.9",
# 		  Sepal.Width = "3.1", Petal.Length = "1.5", Petal.Width = "0.2",
# 		  Species = "setosa", Sepal.Length = "5.0", Sepal.Width = "3.2",
# 		  Petal.Length = "1.2", Petal.Width = "0.2", Species = "setosa",
# 		  Sepal.Length = "5.5", Sepal.Width = "3.5", Petal.Length = "1.3",
# 		  Petal.Width = "0.2", Species = "setosa", Sepal.Length = "4.9",
# 		  Sepal.Width = "3.6", Petal.Length = "1.4", Petal.Width = "0.1",
# 		  Species = "setosa", Sepal.Length = "4.4", Sepal.Width = "3.0",
# 		  Petal.Length = "1.3", Petal.Width = "0.2", Species = "setosa",
# 		  Sepal.Length = "5.1", Sepal.Width = "3.4", Petal.Length = "1.5",
# 		  Petal.Width = "0.2", Species = "setosa", Sepal.Length = "5.0",
# 		  Sepal.Width = "3.5", Petal.Length = "1.3", Petal.Width = "0.3",
# 		  Species = "setosa", Sepal.Length = "4.5", Sepal.Width = "2.3",
# 		  Petal.Length = "1.3", Petal.Width = "0.3", Species = "setosa",
# 		  Sepal.Length = "4.4", Sepal.Width = "3.2", Petal.Length = "1.3",
# 		  Petal.Width = "0.2", Species = "setosa", Sepal.Length = "5.0",
# 		  Sepal.Width = "3.5", Petal.Length = "1.6", Petal.Width = "0.6",
# 		  Species = "setosa", Sepal.Length = "5.1", Sepal.Width = "3.8",
# 		  Petal.Length = "1.9", Petal.Width = "0.4", Species = "setosa",
# 		  Sepal.Length = "4.8", Sepal.Width = "3.0", Petal.Length = "1.4",
# 		  Petal.Width = "0.3", Species = "setosa", Sepal.Length = "5.1",
# 		  Sepal.Width = "3.8", Petal.Length = "1.6", Petal.Width = "0.2",
# 		  Species = "setosa", Sepal.Length = "4.6", Sepal.Width = "3.2",
# 		  Petal.Length = "1.4", Petal.Width = "0.2", Species = "setosa",
# 		  Sepal.Length = "5.3", Sepal.Width = "3.7", Petal.Length = "1.5",
# 		  Petal.Width = "0.2", Species = "setosa", Sepal.Length = "5.0",
# 		  Sepal.Width = "3.3", Petal.Length = "1.4", Petal.Width = "0.2",
# 		  Species = "setosa", Sepal.Length = "7.0", Sepal.Width = "3.2",
# 		  Petal.Length = "4.7", Petal.Width = "1.4", Species = "versicolor",
# 		  Sepal.Length = "6.4", Sepal.Width = "3.2", Petal.Length = "4.5",
# 		  Petal.Width = "1.5", Species = "versicolor", Sepal.Length = "6.9",
# 		  Sepal.Width = "3.1", Petal.Length = "4.9", Petal.Width = "1.5",
# 		  Species = "versicolor", Sepal.Length = "5.5", Sepal.Width = "2.3",
# 		  Petal.Length = "4.0", Petal.Width = "1.3", Species = "versicolor",
# 		  Sepal.Length = "6.5", Sepal.Width = "2.8", Petal.Length = "4.6",
# 		  Petal.Width = "1.5", Species = "versicolor", Sepal.Length = "5.7",
# 		  Sepal.Width = "2.8", Petal.Length = "4.5", Petal.Width = "1.3",
# 		  Species = "versicolor", Sepal.Length = "6.3", Sepal.Width = "3.3",
# 		  Petal.Length = "4.7", Petal.Width = "1.6", Species = "versicolor",
# 		  Sepal.Length = "4.9", Sepal.Width = "2.4", Petal.Length = "3.3",
# 		  Petal.Width = "1.0", Species = "versicolor", Sepal.Length = "6.6",
# 		  Sepal.Width = "2.9", Petal.Length = "4.6", Petal.Width = "1.3",
# 		  Species = "versicolor", Sepal.Length = "5.2", Sepal.Width = "2.7",
# 		  Petal.Length = "3.9", Petal.Width = "1.4", Species = "versicolor",
# 		  Sepal.Length = "5.0", Sepal.Width = "2.0", Petal.Length = "3.5",
# 		  Petal.Width = "1.0", Species = "versicolor", Sepal.Length = "5.9",
# 		  Sepal.Width = "3.0", Petal.Length = "4.2", Petal.Width = "1.5",
# 		  Species = "versicolor", Sepal.Length = "6.0", Sepal.Width = "2.2",
# 		  Petal.Length = "4.0", Petal.Width = "1.0", Species = "versicolor",
# 		  Sepal.Length = "6.1", Sepal.Width = "2.9", Petal.Length = "4.7",
# 		  Petal.Width = "1.4", Species = "versicolor", Sepal.Length = "5.6",
# 		  Sepal.Width = "2.9", Petal.Length = "3.6", Petal.Width = "1.3",
# 		  Species = "versicolor", Sepal.Length = "6.7", Sepal.Width = "3.1",
# 		  Petal.Length = "4.4", Petal.Width = "1.4", Species = "versicolor",
# 		  Sepal.Length = "5.6", Sepal.Width = "3.0", Petal.Length = "4.5",
# 		  Petal.Width = "1.5", Species = "versicolor", Sepal.Length = "5.8",
# 		  Sepal.Width = "2.7", Petal.Length = "4.1", Petal.Width = "1.0",
# 		  Species = "versicolor", Sepal.Length = "6.2", Sepal.Width = "2.2",
# 		  Petal.Length = "4.5", Petal.Width = "1.5", Species = "versicolor",
# 		  Sepal.Length = "5.6", Sepal.Width = "2.5", Petal.Length = "3.9",
# 		  Petal.Width = "1.1", Species = "versicolor", Sepal.Length = "5.9",
# 		  Sepal.Width = "3.2", Petal.Length = "4.8", Petal.Width = "1.8",
# 		  Species = "versicolor", Sepal.Length = "6.1", Sepal.Width = "2.8",
# 		  Petal.Length = "4.0", Petal.Width = "1.3", Species = "versicolor",
# 		  Sepal.Length = "6.3", Sepal.Width = "2.5", Petal.Length = "4.9",
# 		  Petal.Width = "1.5", Species = "versicolor", Sepal.Length = "6.1",
# 		  Sepal.Width = "2.8", Petal.Length = "4.7", Petal.Width = "1.2",
# 		  Species = "versicolor", Sepal.Length = "6.4", Sepal.Width = "2.9",
# 		  Petal.Length = "4.3", Petal.Width = "1.3", Species = "versicolor",
# 		  Sepal.Length = "6.6", Sepal.Width = "3.0", Petal.Length = "4.4",
# 		  Petal.Width = "1.4", Species = "versicolor", Sepal.Length = "6.8",
# 		  Sepal.Width = "2.8", Petal.Length = "4.8", Petal.Width = "1.4",
# 		  Species = "versicolor", Sepal.Length = "6.7", Sepal.Width = "3.0",
# 		  Petal.Length = "5.0", Petal.Width = "1.7", Species = "versicolor",
# 		  Sepal.Length = "6.0", Sepal.Width = "2.9", Petal.Length = "4.5",
# 		  Petal.Width = "1.5", Species = "versicolor", Sepal.Length = "5.7",
# 		  Sepal.Width = "2.6", Petal.Length = "3.5", Petal.Width = "1.0",
# 		  Species = "versicolor", Sepal.Length = "5.5", Sepal.Width = "2.4",
# 		  Petal.Length = "3.8", Petal.Width = "1.1", Species = "versicolor",
# 		  Sepal.Length = "5.5", Sepal.Width = "2.4", Petal.Length = "3.7",
# 		  Petal.Width = "1.0", Species = "versicolor", Sepal.Length = "5.8",
# 		  Sepal.Width = "2.7", Petal.Length = "3.9", Petal.Width = "1.2",
# 		  Species = "versicolor", Sepal.Length = "6.0", Sepal.Width = "2.7",
# 		  Petal.Length = "5.1", Petal.Width = "1.6", Species = "versicolor",
# 		  Sepal.Length = "5.4", Sepal.Width = "3.0", Petal.Length = "4.5",
# 		  Petal.Width = "1.5", Species = "versicolor", Sepal.Length = "6.0",
# 		  Sepal.Width = "3.4", Petal.Length = "4.5", Petal.Width = "1.6",
# 		  Species = "versicolor", Sepal.Length = "6.7", Sepal.Width = "3.1",
# 		  Petal.Length = "4.7", Petal.Width = "1.5", Species = "versicolor",
# 		  Sepal.Length = "6.3", Sepal.Width = "2.3", Petal.Length = "4.4",
# 		  Petal.Width = "1.3", Species = "versicolor", Sepal.Length = "5.6",
# 		  Sepal.Width = "3.0", Petal.Length = "4.1", Petal.Width = "1.3",
# 		  Species = "versicolor", Sepal.Length = "5.5", Sepal.Width = "2.5",
# 		  Petal.Length = "4.0", Petal.Width = "1.3", Species = "versicolor",
# 		  Sepal.Length = "5.5", Sepal.Width = "2.6", Petal.Length = "4.4",
# 		  Petal.Width = "1.2", Species = "versicolor", Sepal.Length = "6.1",
# 		  Sepal.Width = "3.0", Petal.Length = "4.6", Petal.Width = "1.4",
# 		  Species = "versicolor", Sepal.Length = "5.8", Sepal.Width = "2.6",
# 		  Petal.Length = "4.0", Petal.Width = "1.2", Species = "versicolor",
# 		  Sepal.Length = "5.0", Sepal.Width = "2.3", Petal.Length = "3.3",
# 		  Petal.Width = "1.0", Species = "versicolor", Sepal.Length = "5.6",
# 		  Sepal.Width = "2.7", Petal.Length = "4.2", Petal.Width = "1.3",
# 		  Species = "versicolor", Sepal.Length = "5.7", Sepal.Width = "3.0",
# 		  Petal.Length = "4.2", Petal.Width = "1.2", Species = "versicolor",
# 		  Sepal.Length = "5.7", Sepal.Width = "2.9", Petal.Length = "4.2",
# 		  Petal.Width = "1.3", Species = "versicolor", Sepal.Length = "6.2",
# 		  Sepal.Width = "2.9", Petal.Length = "4.3", Petal.Width = "1.3",
# 		  Species = "versicolor", Sepal.Length = "5.1", Sepal.Width = "2.5",
# 		  Petal.Length = "3.0", Petal.Width = "1.1", Species = "versicolor",
# 		  Sepal.Length = "5.7", Sepal.Width = "2.8", Petal.Length = "4.1",
# 		  Petal.Width = "1.3", Species = "versicolor", Sepal.Length = "6.3",
# 		  Sepal.Width = "3.3", Petal.Length = "6.0", Petal.Width = "2.5",
# 		  Species = "virginica", Sepal.Length = "5.8", Sepal.Width = "2.7",
# 		  Petal.Length = "5.1", Petal.Width = "1.9", Species = "virginica",
# 		  Sepal.Length = "7.1", Sepal.Width = "3.0", Petal.Length = "5.9",
# 		  Petal.Width = "2.1", Species = "virginica", Sepal.Length = "6.3",
# 		  Sepal.Width = "2.9", Petal.Length = "5.6", Petal.Width = "1.8",
# 		  Species = "virginica", Sepal.Length = "6.5", Sepal.Width = "3.0",
# 		  Petal.Length = "5.8", Petal.Width = "2.2", Species = "virginica",
# 		  Sepal.Length = "7.6", Sepal.Width = "3.0", Petal.Length = "6.6",
# 		  Petal.Width = "2.1", Species = "virginica", Sepal.Length = "4.9",
# 		  Sepal.Width = "2.5", Petal.Length = "4.5", Petal.Width = "1.7",
# 		  Species = "virginica", Sepal.Length = "7.3", Sepal.Width = "2.9",
# 		  Petal.Length = "6.3", Petal.Width = "1.8", Species = "virginica",
# 		  Sepal.Length = "6.7", Sepal.Width = "2.5", Petal.Length = "5.8",
# 		  Petal.Width = "1.8", Species = "virginica", Sepal.Length = "7.2",
# 		  Sepal.Width = "3.6", Petal.Length = "6.1", Petal.Width = "2.5",
# 		  Species = "virginica", Sepal.Length = "6.5", Sepal.Width = "3.2",
# 		  Petal.Length = "5.1", Petal.Width = "2.0", Species = "virginica",
# 		  Sepal.Length = "6.4", Sepal.Width = "2.7", Petal.Length = "5.3",
# 		  Petal.Width = "1.9", Species = "virginica", Sepal.Length = "6.8",
# 		  Sepal.Width = "3.0", Petal.Length = "5.5", Petal.Width = "2.1",
# 		  Species = "virginica", Sepal.Length = "5.7", Sepal.Width = "2.5",
# 		  Petal.Length = "5.0", Petal.Width = "2.0", Species = "virginica",
# 		  Sepal.Length = "5.8", Sepal.Width = "2.8", Petal.Length = "5.1",
# 		  Petal.Width = "2.4", Species = "virginica", Sepal.Length = "6.4",
# 		  Sepal.Width = "3.2", Petal.Length = "5.3", Petal.Width = "2.3",
# 		  Species = "virginica", Sepal.Length = "6.5", Sepal.Width = "3.0",
# 		  Petal.Length = "5.5", Petal.Width = "1.8", Species = "virginica",
# 		  Sepal.Length = "7.7", Sepal.Width = "3.8", Petal.Length = "6.7",
# 		  Petal.Width = "2.2", Species = "virginica", Sepal.Length = "7.7",
# 		  Sepal.Width = "2.6", Petal.Length = "6.9", Petal.Width = "2.3",
# 		  Species = "virginica", Sepal.Length = "6.0", Sepal.Width = "2.2",
# 		  Petal.Length = "5.0", Petal.Width = "1.5", Species = "virginica",
# 		  Sepal.Length = "6.9", Sepal.Width = "3.2", Petal.Length = "5.7",
# 		  Petal.Width = "2.3", Species = "virginica", Sepal.Length = "5.6",
# 		  Sepal.Width = "2.8", Petal.Length = "4.9", Petal.Width = "2.0",
# 		  Species = "virginica", Sepal.Length = "7.7", Sepal.Width = "2.8",
# 		  Petal.Length = "6.7", Petal.Width = "2.0", Species = "virginica",
# 		  Sepal.Length = "6.3", Sepal.Width = "2.7", Petal.Length = "4.9",
# 		  Petal.Width = "1.8", Species = "virginica", Sepal.Length = "6.7",
# 		  Sepal.Width = "3.3", Petal.Length = "5.7", Petal.Width = "2.1",
# 		  Species = "virginica", Sepal.Length = "7.2", Sepal.Width = "3.2",
# 		  Petal.Length = "6.0", Petal.Width = "1.8", Species = "virginica",
# 		  Sepal.Length = "6.2", Sepal.Width = "2.8", Petal.Length = "4.8",
# 		  Petal.Width = "1.8", Species = "virginica", Sepal.Length = "6.1",
# 		  Sepal.Width = "3.0", Petal.Length = "4.9", Petal.Width = "1.8",
# 		  Species = "virginica", Sepal.Length = "6.4", Sepal.Width = "2.8",
# 		  Petal.Length = "5.6", Petal.Width = "2.1", Species = "virginica",
# 		  Sepal.Length = "7.2", Sepal.Width = "3.0", Petal.Length = "5.8",
# 		  Petal.Width = "1.6", Species = "virginica", Sepal.Length = "7.4",
# 		  Sepal.Width = "2.8", Petal.Length = "6.1", Petal.Width = "1.9",
# 		  Species = "virginica", Sepal.Length = "7.9", Sepal.Width = "3.8",
# 		  Petal.Length = "6.4", Petal.Width = "2.0", Species = "virginica",
# 		  Sepal.Length = "6.4", Sepal.Width = "2.8", Petal.Length = "5.6",
# 		  Petal.Width = "2.2", Species = "virginica", Sepal.Length = "6.3",
# 		  Sepal.Width = "2.8", Petal.Length = "5.1", Petal.Width = "1.5",
# 		  Species = "virginica", Sepal.Length = "6.1", Sepal.Width = "2.6",
# 		  Petal.Length = "5.6", Petal.Width = "1.4", Species = "virginica",
# 		  Sepal.Length = "7.7", Sepal.Width = "3.0", Petal.Length = "6.1",
# 		  Petal.Width = "2.3", Species = "virginica", Sepal.Length = "6.3",
# 		  Sepal.Width = "3.4", Petal.Length = "5.6", Petal.Width = "2.4",
# 		  Species = "virginica", Sepal.Length = "6.4", Sepal.Width = "3.1",
# 		  Petal.Length = "5.5", Petal.Width = "1.8", Species = "virginica",
# 		  Sepal.Length = "6.0", Sepal.Width = "3.0", Petal.Length = "4.8",
# 		  Petal.Width = "1.8", Species = "virginica", Sepal.Length = "6.9",
# 		  Sepal.Width = "3.1", Petal.Length = "5.4", Petal.Width = "2.1",
# 		  Species = "virginica", Sepal.Length = "6.7", Sepal.Width = "3.1",
# 		  Petal.Length = "5.6", Petal.Width = "2.4", Species = "virginica",
# 		  Sepal.Length = "6.9", Sepal.Width = "3.1", Petal.Length = "5.1",
# 		  Petal.Width = "2.3", Species = "virginica", Sepal.Length = "5.8",
# 		  Sepal.Width = "2.7", Petal.Length = "5.1", Petal.Width = "1.9",
# 		  Species = "virginica", Sepal.Length = "6.8", Sepal.Width = "3.2",
# 		  Petal.Length = "5.9", Petal.Width = "2.3", Species = "virginica",
# 		  Sepal.Length = "6.7", Sepal.Width = "3.3", Petal.Length = "5.7",
# 		  Petal.Width = "2.5", Species = "virginica", Sepal.Length = "6.7",
# 		  Sepal.Width = "3.0", Petal.Length = "5.2", Petal.Width = "2.3",
# 		  Species = "virginica", Sepal.Length = "6.3", Sepal.Width = "2.5",
# 		  Petal.Length = "5.0", Petal.Width = "1.9", Species = "virginica",
# 		  Sepal.Length = "6.5", Sepal.Width = "3.0", Petal.Length = "5.2",
# 		  Petal.Width = "2.0", Species = "virginica", Sepal.Length = "6.2",
# 		  Sepal.Width = "3.4", Petal.Length = "5.4", Petal.Width = "2.3",
# 		  Species = "virginica", Sepal.Length = "5.9", Sepal.Width = "3.0",
# 		  Petal.Length = "5.1", Petal.Width = "1.8", Species = "virginica"
# )
# temp %>% str
